name: Checking code quality

on:
  push:

jobs:
  check-code-quality:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setting up node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - name: npm install
        run: npm ci --no-fund --no-audit
      - name: lint
        run: npm run lint
      - name: test
        run: |
          npm run test:ci
      - name: build
        run: npm run build
